#!/bin/bash

SOURCES=src/*.js
TARGET=downstream.js

echo "[concat] source: $SOURCES"
echo "[concat] target: downstream.js"
cat src/?-*.js > downstream.js
WCRESULT="`wc -c $TARGET | sed -e 's/^ *//'`"
echo "[result] $WCRESULT"
echo "[done]   build finished at `date`"
echo
