#!/usr/bin/env node

var fs = require('fs');

var args = process.argv.slice(2);

console.log('Watching files:', args.join(' '));

args.forEach(function(file) {
    fs.watch(file, { recursive: true }, function(event, filename) {
        console.log(filename + ':', event);
        setTimeout(process.exit(), 50);
    });
})
