#!/usr/bin/env node

var fs = require('fs');

var args = process.argv.slice(2);

console.log('[watch]  watching', args.length,'files');

args.forEach(function(file) {
    fs.watch(file, { recursive: true }, function(event, filename) {
        console.log('[watch]', filename + ':', event);
        setTimeout(process.exit, 550);
    });
})
